configuration:
  app:
    name: url_shortener
    version: 0.1
  api:
    port: 8080
    host: localhost
  log:
    level: debug
  postgresql:
    host: localhost
    port: 5432
    user: postgres
    password: root
    dbName: url
    SSL: false
    SSLCertificatePath:
  cache:
    url: http://localhost:8081/store
